### ISSUE TITLE
Ensure ImageJ works with iRODS for BRAIN-I

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#16]
Erik, Jonathan Crabtree, and Don Sizemore to connect with Mike Conway and double check that nothing more needs to be done with ImageJ.

Milestone: #2

**Comment by donsizemore** [comment]
We have ImageJ loaded on the data analysis PC at Neuroscience and on my test data analysis box here at Odum. The MyCloudJ CloudConnect plugin is an iRODS file transfer plugin for ImageJ, but won't meet our needs because it won't accept AVU metadata. We'll have Neuroscience use iDrop for this purpose.
